
default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: backend_development
  username: postgres
  password: 4kayamoses

test:
  <<: *default
  database: backend_test
  username: postgres
  password: 4kayamoses

production:
  <<: *default
  database: backend_production
